### ISSUE TITLE
Is it possible to adapt VariBAD to environments with images as observations?

### ISSUE THREAD

**Issue by luizapozzobon** [lmzintgraf/varibad#14]
Hey, Dr. Zintgraf. First, thanks for your inspiring work with VariBAD, HyperX, and other contributions.

I'd like to know if these methods can be adapted to accept image observations of games such as Procgen and Atari. 

My initial intuition is that it would be possible by changing the policy networks, but I'd like to verify if there are any theoretical barriers I'm not currently seeing, as I'm just starting in this literature and haven't seen any applications of these methods to such environments.

Thanks!!

**Comment by lmzintgraf** [comment]
Hi Luiza, thanks for your interest in our work :) 

Yes, these methods should also work for image observations! There are no theoretical barriers, it might just take longer to train since the networks will be bigger, and the tasks likely harder. I would first implement this in a simple gridworld and compare it to a baseline that doesn't work on images (but takes x/y positions as inputs for example).

To support image observations, you have to:
- Change the policy network (as you already said), for example using a convnet.
- Change both the VAE encoder and decoder. For the decoder, I would suggest you *don't* use an observation decoder, but only a reward decoder. Otherwise, the decoder will try to re-create the image observations, which is going to be overkill and could cause problems with VAE training. And in ProcGen/Atari the transition function doesn't change, so you don't need an observation decoder anyway. Further, I would probably structure the decoder so that you have separate embedding pipelines for the observations (using conv layers), the actions  (using for example just one linear layer), and the latent samples (same as actions), making sure that when you concatenate them, they're all roughly equally sized. 

Hope this helps!

**Comment by luizapozzobon** [comment]
Thanks for the tips, they helped a bunch! I will give it a go at adapting it.
