### ISSUE TITLE
Meta-world implementation question

### ISSUE THREAD

**Issue by ho-range** [lmzintgraf/varibad#18]
Hi, I'm trying to implement VariBAD algorithm to Meta-World environment. 
I've read your result graphs on ML1 tasks of meta-world environments, https://www.jmlr.org/papers/volume22/21-0657/21-0657.pdf (Appendix D)
but I couldn't find the meta-world implementation details in this repo. 

Did you design meta-world wrapper on your own? how can you implement that? I wonder how could I implement this. 
Are there some helpful links you know about varibad metaworld implementation? 

Thanks a lot!

**Comment by lmzintgraf** [comment]
I didn't include the Meta-World experiments in the public repository since (1) the files were huge and I had to fork the entire codebase to get around the issues with np.random and (2) in the meantime v2 of Meta-World came out which is much better, and which I'd advise on using if you want to do research on Meta-World. 

If you want to reproduce the results in the paper, you have to fork the Meta-World (v1) and change it such that it doesn't use the np.random, but replace all of those with the python random calls (see an example in my repo). The v1 of Meta-World is quite outdated though, and if you want to work with Meta-World it's probably best to work with v2 - it's much better since they made some changes that make it easier to learn, and I'd expect results to be better. I never got around to trying this out since the code from v1 to v2 changed quite a bit, and it wasn't an easy drop-in to try.
