### ISSUE TITLE
Asking about the number of tasks

### ISSUE THREAD

**Issue by adamphung-ho** [lmzintgraf/varibad#22]
Hi, I'm working on reproducing your work as a baseline for my POMDP tasks. In one of the tasks, where the number of tasks is only 2, I split 1 task for training and the other for evaluation. Upon examining the policy's performance, I noticed that the policy quickly learns the training task. However, during evaluation, the agent behaves as though it's still in the training task, resulting in very poor performance on the evaluation task. Additionally, in my task, there are certain states that reveal information about the goal, but the policy doesn't reach these states, indicating a lack of information-seeking behavior. Could these issues be related to the limited number of tasks?

**Comment by lmzintgraf** [comment]
Hi, if you have only one task for training and evaluate on a single other task, this is not expected to work. That's because the agent will overfit to solving the single training task. Usually you need many more training tasks, and have the test task not be outside of the prior task distribution.

About the information-seeking behaviour: given that there's only one training task, the agent doesn't need to learn the information-seeking behaviour - it can just learn the single task directly. If you had a wider coverage of training tasks, it might learn the information-seeking behaviour, but that depends on how hard it is to learn this. We have a follow-up paper where we look more into the challenge of learning exploration, see the HyperX [paper](https://arxiv.org/abs/2010.01062) and [codebase](https://github.com/lmzintgraf/hyperx).
